admin.dashboard.index:
    path: /admin/dashboard/index
    defaults:
        _controller: 'dashboard.controller.admin:indexAction'
    options:
        require_admin_permission: dashboard.index
admin.user.index:
    path: /admin/user/index
    defaults:
        _controller: 'user.controller.admin:indexAction'
    options:
        require_admin_permission: user.index
admin.user.grid:
    path: /admin/user/grid
    defaults:
        _controller: 'user.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: user.index
admin.user.add:
    path: /admin/user/add
    defaults:
        _controller: 'user.controller.admin:addAction'
    options:
        require_admin_permission: user.add
admin.user.edit:
    path: '/admin/user/edit/{id}'
    defaults:
        _controller: 'user.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: user.edit
admin.user.delete:
    path: '/admin/user/delete/{id}'
    defaults:
        _controller: 'user.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: user.delete
admin.user.login:
    path: /admin/user/login
    defaults:
        _controller: 'user.controller.admin:loginAction'
    options: {  }
admin.user.reset_password:
    path: /admin/user/reset
    defaults:
        _controller: 'user.controller.admin:resetPasswordAction'
    options: {  }
admin.user.login_check:
    path: /admin/user/login_check
    options: {  }
admin.user.logout:
    path: /admin/user/logout
    options: {  }
admin.user_group.index:
    path: /admin/user/group/index
    defaults:
        _controller: 'user_group.controller.admin:indexAction'
    options:
        require_admin_permission: user_group.index
admin.user_group.grid:
    path: /admin/user/group/grid
    defaults:
        _controller: 'user_group.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: user_group.index
admin.user_group.add:
    path: /admin/user/group/add
    defaults:
        _controller: 'user_group.controller.admin:addAction'
    options:
        require_admin_permission: user_group.add
admin.user_group.edit:
    path: '/admin/user/group/edit/{id}'
    defaults:
        _controller: 'user_group.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: user_group.edit
admin.user_group.delete:
    path: '/admin/user/group/delete/{id}'
    defaults:
        _controller: 'user_group.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: user_group.delete
