well_commerce_admin:
    configuration:
        admin_menu:
            orm:
                factory: WellCommerce\Bundle\AdminBundle\Factory\AdminMenuFactory
                repository: WellCommerce\Bundle\AdminBundle\Repository\AdminMenuRepository
                mapping: "@WellCommerceAdminBundle/Resources/config/doctrine/AdminMenu.orm.yml"
                entity: WellCommerce\Bundle\AdminBundle\Entity\AdminMenu
        role:
            orm:
                factory: WellCommerce\Bundle\AdminBundle\Factory\RoleFactory
                repository: WellCommerce\Bundle\AdminBundle\Repository\RoleRepository
                mapping: "@WellCommerceAdminBundle/Resources/config/doctrine/Role.orm.yml"
                entity: WellCommerce\Bundle\AdminBundle\Entity\Role
        user:
            orm:
                factory: WellCommerce\Bundle\AdminBundle\Factory\UserFactory
                repository: WellCommerce\Bundle\AdminBundle\Repository\UserRepository
                mapping: "@WellCommerceAdminBundle/Resources/config/doctrine/User.orm.yml"
                entity: WellCommerce\Bundle\AdminBundle\Entity\User
        user_group:
            orm:
                factory: WellCommerce\Bundle\AdminBundle\Factory\UserGroupFactory
                repository: WellCommerce\Bundle\AdminBundle\Repository\UserGroupRepository
                mapping: "@WellCommerceAdminBundle/Resources/config/doctrine/UserGroup.orm.yml"
                entity: WellCommerce\Bundle\AdminBundle\Entity\UserGroup
        user_group_permission:
            orm:
                mapping: "@WellCommerceAdminBundle/Resources/config/doctrine/UserGroupPermission.orm.yml"
                entity: WellCommerce\Bundle\AdminBundle\Entity\UserGroupPermission
